abstract: A Perl interface to the Rakuten WebService API
author: Hideaki Tanaka <tanakahda@gmail.com>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: WebService-Rakuten
no_index: 
  directory: 
    - inc
    - t
requires: 
  Carp: 0
  Class::Accessor::Fast: 0
  Data::Page: 0
  LWP: 0
  Readonly: 0
  URI: 0
  XML::Simple: 0
version: 0.02
